spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: 123.56.65.239:9300
  redis:
    host: 116.62.38.97
    port: 63799
    password: root
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      suffix: .jsp
      prefix: /
mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.wzh.bishe.entity

logging:
  level:
    root: info
    com.wzh.bishe.dao: debug
server:
  servlet:
    jsp:
      init-parameters:
        development: true
